<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Data &amp; Methods</title>

<script src="site_libs/header-attrs-2.30/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="css/styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">NYC Subway & Weather</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="model.html">Analysis</a>
</li>
<li>
  <a href="data.html">Data &amp; Methods</a>
</li>
<li>
  <a href="report.html">Report</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Data &amp; Methods</h1>

</div>


<p>We acquired four datasets for analyzing weather and event impacts on
Manhattan subway ridership (2024-2025). This page documents both our
data sources and the wrangling pipeline that transforms raw data into
analysis-ready panels.</p>
<hr />
<div id="part-1-data-sources" class="section level1">
<h1>Part 1: Data Sources</h1>
<div id="mta-subway-ridership" class="section level2">
<h2>MTA Subway Ridership</h2>
<p><strong>The Disaggregation Challenge:</strong></p>
<p>The MTA ridership dataset is highly disaggregated to capture detailed
fare collection patterns. Each hourly observation is broken down by:</p>
<ul>
<li><strong>11+ fare class categories</strong>: Full Fare,
Senior/Disabled, Students (K-12 and college), Fair Fares (reduced-income
riders), and various pass types (7-day, 30-day, unlimited)</li>
<li><strong>2 payment methods</strong>: MetroCard (legacy magnetic
stripe) and OMNY (contactless tap-to-pay)</li>
</ul>
<p>This granularity creates a data explosion problem. For Manhattan’s
123 stations during a single week:</p>
<p><strong>123 stations × 24 hours × 7 days × 11 fare categories × 2
payment methods = 227,304 records per week</strong></p>
<p>For our complete 2024-2025 dataset (22 months ≈ 95 weeks), this would
generate <strong>21.6 million records</strong>—far exceeding the Socrata
API’s 100,000-record pagination limit and creating unwieldy file sizes
for analysis.</p>
<p><strong>The Solution:</strong></p>
<p>Since our research questions focus on <em>total ridership</em> rather
than fare type breakdowns, we leveraged the Socrata API’s server-side
aggregation capabilities. Using <code>SUM()</code> with
<code>$group</code>, we aggregated across all fare types and payment
methods <em>before</em> data transfer.</p>
<pre class="r"><code>&quot;$select&quot; = &quot;transit_timestamp, station_complex_id, station_complex,
             borough, SUM(ridership) as total_ridership&quot;,
&quot;$group&quot; = &quot;transit_timestamp, station_complex_id, station_complex, borough&quot;</code></pre>
<p>This reduced records by <strong>96%</strong> (from 21.6M to 1.92M),
making monthly downloads feasible within API limits while preserving the
station-hour granularity needed for our weather and event analyses.</p>
<p>This yielded 1,921,163 hourly observations across 123 Manhattan
stations from 2024-01-01 to 2025-10-19.</p>
<pre class="r"><code># Daily trend (2024 only) with 7-day rolling average
daily_ridership &lt;- ridership |&gt;
  filter(year(date) == 2024) |&gt;
  group_by(date) |&gt;
  summarize(total = sum(total_ridership, na.rm = TRUE) / 1e6, .groups = &quot;drop&quot;) |&gt;
  arrange(date) |&gt;
  mutate(
    rolling_avg = slide_dbl(total, mean, .before = 3, .after = 3, .complete = TRUE)
  )

p_daily &lt;- daily_ridership |&gt;
  ggplot(aes(x = date)) +
  geom_line(aes(y = total), color = okabe_ito$blue, alpha = 0.3, linewidth = 0.4) +
  geom_line(aes(y = rolling_avg), color = okabe_ito$blue, linewidth = 0.9) +
  scale_y_continuous(labels = comma) +
  labs(
    title = &quot;Manhattan Subway Daily Ridership (2024)&quot;,
    subtitle = &quot;7-day rolling average (bold) with daily values (faded)&quot;,
    x = NULL, y = &quot;Daily Ridership (M)&quot;
  ) +
  theme(plot.title = element_text(size = 11), plot.subtitle = element_text(size = 9))

# Hourly pattern
p_hourly &lt;- ridership |&gt;
  mutate(weekday_type = ifelse(wday(date) %in% 2:6, &quot;Weekday&quot;, &quot;Weekend&quot;)) |&gt;
  group_by(hour, weekday_type) |&gt;
  summarize(avg = mean(total_ridership, na.rm = TRUE) / 1000, .groups = &quot;drop&quot;) |&gt;
  ggplot(aes(x = hour, y = avg, color = weekday_type)) +
  geom_line(linewidth = 1) +
  scale_color_manual(values = c(&quot;Weekday&quot; = okabe_ito$blue, &quot;Weekend&quot; = okabe_ito$vermillion)) +
  labs(title = &quot;Average Hourly Pattern&quot;, x = &quot;Hour&quot;, y = &quot;Avg Ridership (K)&quot;, color = NULL) +
  theme(legend.position = &quot;top&quot;, plot.title = element_text(size = 11))

# Top stations
p_top &lt;- ridership |&gt;
  group_by(station_complex) |&gt;
  summarize(total = sum(total_ridership, na.rm = TRUE) / 1e6, .groups = &quot;drop&quot;) |&gt;
  slice_max(total, n = 30) |&gt;
  arrange(total) |&gt;
  mutate(
    # Truncate station names at first &#39;(&#39; for cleaner display
    station_short = str_replace(station_complex, &quot;\\s*\\(.*&quot;, &quot;&quot;),
    # Make names unique by adding row number suffix if duplicates exist
    station_short = make.unique(station_short, sep = &quot; &quot;),
    # Use factor with levels in current order to preserve sorting
    station_short = factor(station_short, levels = station_short)
  ) |&gt;
  ggplot(aes(x = total, y = station_short)) +
  geom_col(fill = okabe_ito$green) +
  scale_x_continuous(labels = comma) +
  labs(title = &quot;Top 30 Manhattan Stations&quot;, x = &quot;Total Ridership (M)&quot;, y = NULL) +
  theme(plot.title = element_text(size = 11), axis.text.y = element_text(size = 8))

p_top | (p_daily / p_hourly)</code></pre>
<p><img src="images/data-plot_ridership-1.png" width="960" /></p>
<hr />
</div>
<div id="weather-data" class="section level2">
<h2>Weather Data</h2>
<p>The NOAA API requires an authentication token, which we obtained from
<a href="https://www.ncdc.noaa.gov/cdo-web/token">NOAA’s token request
page</a>. After receiving the token via email, we downloaded daily
weather data for Central Park (located in Manhattan) covering 2020-2025.
This provides consistent weather measurements applicable to all
Manhattan stations.</p>
<pre class="r"><code>weather &lt;- read_csv(&#39;data/weather/central_park_weather_wide.csv&#39;, show_col_types = FALSE) |&gt;
  mutate(date = as.Date(date))</code></pre>
<p>The dataset contains 2,151 daily observations with max temperature,
precipitation, and snowfall.</p>
<pre class="r"><code># Temperature and precipitation time series
p_ts &lt;- weather |&gt;
  filter(year(date) &gt;= 2024) |&gt;
  select(date, TMAX, PRCP) |&gt;
  pivot_longer(cols = -date, names_to = &quot;metric&quot;, values_to = &quot;value&quot;) |&gt;
  mutate(metric = ifelse(metric == &quot;TMAX&quot;, &quot;Max Temp (°F)&quot;, &quot;Precipitation (in)&quot;)) |&gt;
  ggplot(aes(x = date, y = value)) +
  geom_line(data = \(x) filter(x, metric == &quot;Max Temp (°F)&quot;), color = okabe_ito$vermillion, linewidth = 0.6) +
  geom_col(data = \(x) filter(x, metric == &quot;Precipitation (in)&quot;), fill = okabe_ito$sky_blue, alpha = 0.7) +
  facet_wrap(~metric, ncol = 1, scales = &quot;free_y&quot;) +
  labs(title = &quot;Central Park Weather (2024-2025)&quot;, x = NULL, y = NULL)

# Seasonal summary
weather_summary &lt;- weather |&gt;
  filter(year(date) &gt;= 2024) |&gt;
  mutate(
    season = case_when(
      month(date) %in% c(12, 1, 2) ~ &quot;Winter&quot;,
      month(date) %in% c(3, 4, 5) ~ &quot;Spring&quot;,
      month(date) %in% c(6, 7, 8) ~ &quot;Summer&quot;,
      month(date) %in% c(9, 10, 11) ~ &quot;Fall&quot;
    ),
    season = factor(season, levels = c(&quot;Winter&quot;, &quot;Spring&quot;, &quot;Summer&quot;, &quot;Fall&quot;)),
    month_abbr = month(date, label = TRUE, abbr = TRUE)
  )

# Seasonal aggregations
seasonal_weather &lt;- weather_summary |&gt;
  group_by(season) |&gt;
  summarize(
    `Avg Temp (°F)` = mean(TMAX, na.rm = TRUE),
    `Storm Days (≥1in)` = sum(PRCP &gt;= 1, na.rm = TRUE),
    `Heat Days (≥90°F)` = sum(TMAX &gt;= 90, na.rm = TRUE),
    .groups = &quot;drop&quot;
  ) |&gt;
  pivot_longer(cols = -season, names_to = &quot;metric&quot;, values_to = &quot;value&quot;)

# Plot seasonal summary
p_season &lt;- seasonal_weather |&gt;
  ggplot(aes(x = season, y = value)) +
  geom_col(aes(fill = season)) +
  scale_fill_manual(values = c(
    &quot;Winter&quot; = okabe_ito$sky_blue, &quot;Spring&quot; = okabe_ito$green,
    &quot;Summer&quot; = okabe_ito$orange, &quot;Fall&quot; = okabe_ito$pink
  )) +
  facet_wrap(~metric, scales = &quot;free&quot;, ncol = 3) +
  labs(title = &quot;Seasonal Weather Summary&quot;, x = NULL, y = NULL) +
  theme(legend.position = &quot;none&quot;, axis.text.x = element_text(angle = 45, hjust = 1))

p_ts / p_season</code></pre>
<p><img src="images/data-plot_weather-1.png" width="960" /></p>
<hr />
</div>
<div id="permitted-events" class="section level2">
<h2>Permitted Events</h2>
<p>The NYC Permitted Event Information - Historical dataset (bkfu-528j)
contains comprehensive event records but includes hundreds of thousands
of small-scale activities (youth sports, film shoots, farmers markets)
unlikely to significantly impact subway ridership.</p>
<p><strong>Smart Filtering Strategy:</strong></p>
<p>Since the dataset lacks attendance information, we filtered for
<strong>large events</strong> (likely 100+ people) using event
characteristics as proxies:</p>
<ul>
<li><strong>Event types</strong>: Parades, Athletic Races/Tours, Street
Events, Block Parties, Sidewalk Sales</li>
<li><strong>Street impact</strong>: Events requiring full street
closures</li>
<li><strong>Exclusions</strong>: Youth/adult sports leagues, production
events, small farmers markets</li>
</ul>
<p>This filtering reduced from ~2 million total events to
<strong>149,524 large events</strong> across NYC.</p>
<pre class="r"><code>events &lt;- read_csv(&#39;data/events/nyc_large_events_2024_2025.csv&#39;, show_col_types = FALSE) |&gt;
  mutate(start_date = as.Date(start_date_time), end_date = as.Date(end_date_time))

events_analysis &lt;- events |&gt;
  filter(!is.na(start_date)) |&gt;
  mutate(
    month = month(start_date, label = TRUE),
    year_month = format(start_date, &quot;%Y-%m&quot;),
    borough = case_when(
      str_detect(tolower(event_borough), &quot;manhattan&quot;) ~ &quot;Manhattan&quot;,
      str_detect(tolower(event_borough), &quot;brooklyn&quot;) ~ &quot;Brooklyn&quot;,
      str_detect(tolower(event_borough), &quot;queens&quot;) ~ &quot;Queens&quot;,
      str_detect(tolower(event_borough), &quot;bronx&quot;) ~ &quot;The Bronx&quot;,
      str_detect(tolower(event_borough), &quot;staten island&quot;) ~ &quot;Staten Island&quot;,
      TRUE ~ &quot;Other&quot;
    )
  )</code></pre>
<p>Successfully downloaded <strong>149,524</strong> large events (Jan
2024 - Oct 2025), including <strong>53,977</strong> in Manhattan.</p>
<pre class="r"><code># Monthly time series by borough
p_events_time &lt;- events_analysis |&gt;
  count(year_month, borough) |&gt;
  mutate(date = as.Date(paste0(year_month, &quot;-01&quot;))) |&gt;
  ggplot(aes(x = date, y = n, fill = borough)) +
  geom_col() +
  scale_fill_manual(values = c(
    &quot;Manhattan&quot; = okabe_ito$orange, &quot;Brooklyn&quot; = okabe_ito$sky_blue,
    &quot;Queens&quot; = okabe_ito$green, &quot;The Bronx&quot; = okabe_ito$vermillion,
    &quot;Staten Island&quot; = okabe_ito$pink, &quot;Other&quot; = &quot;#999999&quot;
  )) +
  scale_x_date(date_labels = &quot;%b %Y&quot;, date_breaks = &quot;3 months&quot;) +
  labs(title = &quot;Large NYC Events by Borough (2024-2025)&quot;,
       subtitle = &quot;Strong seasonal pattern: summer/fall peaks, winter lows&quot;,
       x = NULL, y = &quot;Number of Events&quot;, fill = &quot;Borough&quot;) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = &quot;right&quot;)

# Top event types in Manhattan
p_event_types &lt;- events_analysis |&gt;
  filter(borough == &quot;Manhattan&quot;, !is.na(event_type)) |&gt;
  count(event_type, sort = TRUE) |&gt;
  slice_max(n, n = 8) |&gt;
  mutate(event_type = fct_reorder(event_type, n)) |&gt;
  ggplot(aes(x = n, y = event_type)) +
  geom_col(fill = &quot;#F77F00&quot;) +
  scale_x_continuous(labels = comma) +
  labs(title = &quot;Top Event Types in Manhattan&quot;, x = &quot;Number of Events&quot;, y = NULL) +
  theme(plot.title = element_text(size = 11))

p_events_time / p_event_types</code></pre>
<p><img src="images/data-plot_events-1.png" width="960" /></p>
<hr />
</div>
<div id="station-locations" class="section level2">
<h2>Station Locations</h2>
<p>Station coordinates are already embedded in the ridership data, so we
extracted unique station complexes with coordinates directly from the
ridership API rather than seeking a separate geospatial dataset.</p>
<pre class="r"><code>stations &lt;- read_csv(&#39;data/stations/mta_station_complexes.csv&#39;, show_col_types = FALSE)
manhattan_stations &lt;- stations |&gt;
  filter(borough == &quot;Manhattan&quot;, !is.na(latitude), !is.na(longitude))</code></pre>
<p>We identified 476 unique station complexes across NYC, with 155 in
Manhattan covering the entire borough from Battery Park to Inwood.</p>
<pre class="r"><code>library(sf)

# Calculate total ridership by station
station_ridership &lt;- ridership |&gt;
  group_by(station_complex_id, station_complex) |&gt;
  summarize(total_ridership = sum(total_ridership, na.rm = TRUE) / 1e6, .groups = &quot;drop&quot;)

# Join with station coordinates
manhattan_stations_ridership &lt;- manhattan_stations |&gt;
  left_join(station_ridership, by = c(&quot;station_complex_id&quot;, &quot;station_complex&quot;)) |&gt;
  mutate(
    longitude = as.numeric(longitude),
    latitude = as.numeric(latitude)
  ) |&gt;
  filter(!is.na(total_ridership))

# Load NYC neighborhoods for map background
# Data preloaded by data/download_nyc_geo.R
nyc_nta &lt;- st_read(&quot;data/geo/nyc_nta.geojson&quot;, quiet = TRUE)

# Filter to Manhattan
if (&quot;borough&quot; %in% names(nyc_nta)) {
  manhattan_sf &lt;- nyc_nta %&gt;% filter(borough == &quot;Manhattan&quot;)
} else if (&quot;boro_name&quot; %in% names(nyc_nta)) {
  manhattan_sf &lt;- nyc_nta %&gt;% filter(boro_name == &quot;Manhattan&quot;)
} else {
  manhattan_sf &lt;- nyc_nta
}

# Create static map
ggplot() +
  geom_sf(data = manhattan_sf, fill = &quot;gray92&quot;, color = &quot;gray75&quot;, linewidth = 0.2) +
  geom_point(
    data = manhattan_stations_ridership,
    aes(x = longitude, y = latitude, color = total_ridership),
    size = 2.5,
    alpha = 0.85
  ) +
  scale_color_viridis_c(
    option = &quot;plasma&quot;,
    name = &quot;Total Ridership\n(Millions)&quot;,
    trans = &quot;log10&quot;,
    labels = scales::comma
  ) +
  coord_sf(
    crs = 4326,
    xlim = c(-74.02, -73.93),
    ylim = c(40.70, 40.80)
  ) +
  labs(
    title = &quot;Manhattan Subway Stations by Total Ridership&quot;,
    subtitle = &quot;January 2024 - October 2025&quot;,
    x = NULL, y = NULL
  ) +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    legend.position = &quot;right&quot;
  )</code></pre>
<p><img src="images/data-plot_stations-1.png" width="768" /></p>
<p><strong>Download scripts:</strong> <a
href="data/download_full_ridership_monthly.R"><code>download_full_ridership_monthly.R</code></a>,
<a
href="data/download_historical_events_monthly.R"><code>download_historical_events_monthly.R</code></a>,
<a
href="data/download_noaa_weather.R"><code>download_noaa_weather.R</code></a></p>
<hr />
</div>
</div>
<div id="part-2-data-wrangling-pipeline" class="section level1">
<h1>Part 2: Data Wrangling Pipeline</h1>
<p>This section documents the complete data wrangling process that
transforms our raw datasets into analysis-ready panels. The goal is to
create a robust foundation for examining the interplay between MTA
subway ridership, weather conditions, and major NYC events.</p>
<div id="raw-data-ingestion" class="section level2">
<h2>Raw Data Ingestion</h2>
<p>We begin by loading the raw datasets and performing initial cleaning:
standardizing column names, parsing date/time stamps, and filtering to
Manhattan for the 2024-2025 study period.</p>
<pre class="r"><code>path_rid_2024 &lt;- &quot;data/mta_ridership_full/ridership_2024_manhattan.csv&quot;
path_rid_2025 &lt;- &quot;data/mta_ridership_full/ridership_2025_manhattan.csv&quot;
path_weather &lt;- &quot;data/weather/central_park_weather_wide.csv&quot;
path_events &lt;- &quot;data/events/nyc_large_events_2024_2025.csv&quot;
path_stations &lt;- &quot;data/stations/mta_station_complexes.csv&quot;

rid24 &lt;- vroom::vroom(path_rid_2024, show_col_types = FALSE)
rid25 &lt;- vroom::vroom(path_rid_2025, show_col_types = FALSE)
weather_raw &lt;- readr::read_csv(path_weather, show_col_types = FALSE)
events_raw &lt;- vroom::vroom(path_events, show_col_types = FALSE)
stations_raw &lt;- readr::read_csv(path_stations, show_col_types = FALSE)

rid &lt;- bind_rows(rid24, rid25) |&gt;
  clean_names() |&gt;
  mutate(
    # Handle both datetime and date-only formats
    transit_timestamp = parse_date_time(transit_timestamp, orders = c(&quot;ymd HMS&quot;, &quot;ymd&quot;), quiet = TRUE),
    date = as_date(transit_timestamp),
    hour = hour(transit_timestamp)
  ) |&gt;
  select(station_complex_id, station_complex, borough, transit_timestamp, date, hour, total_ridership)

weather_clean &lt;- weather_raw |&gt;
  clean_names() |&gt;
  mutate(
    date = as_date(date),
    tmax = as.numeric(tmax),
    prcp = as.numeric(prcp),
    snow = as.numeric(snow)
  ) |&gt;
  select(date, tmax, prcp, snow) |&gt;
  arrange(date)

events_clean &lt;- events_raw |&gt;
  clean_names() |&gt;
  mutate(
    start_dt = ymd_hms(start_date_time, quiet = TRUE),
    end_dt = ymd_hms(end_date_time, quiet = TRUE),
    event_borough = str_to_lower(event_borough)
  ) |&gt;
  filter(!is.na(start_dt), !is.na(end_dt), end_dt &gt;= start_dt)

stations_clean &lt;- stations_raw |&gt;
  clean_names() |&gt;
  filter(str_to_lower(borough) == &quot;manhattan&quot;, !is.na(latitude), !is.na(longitude))</code></pre>
</div>
<div id="station-hour-panel-construction" class="section level2">
<h2>Station-Hour Panel Construction</h2>
<p>The most granular unit of our analysis is the station-hour. We build
the primary <code>panel_station_hour</code> dataset and calculate
<code>hours_present</code> per station-day to identify potential missing
data.</p>
<pre class="r"><code>panel_station_hour &lt;- rid |&gt;
  select(station_complex_id, station_complex, date, hour, total_ridership) |&gt;
  arrange(station_complex_id, date, hour)

hour_cov &lt;- panel_station_hour |&gt;
  group_by(station_complex_id, date) |&gt;
  summarize(hours_present = n_distinct(hour), .groups = &quot;drop&quot;)</code></pre>
</div>
<div id="station-day-aggregation" class="section level2">
<h2>Station-Day Aggregation</h2>
<p>For analyses focusing on daily impacts (e.g., heatwaves), we
aggregate to <code>panel_station_day</code> by summing total ridership
for each station on each day.</p>
<pre class="r"><code>panel_station_day &lt;- panel_station_hour |&gt;
  group_by(station_complex_id, station_complex, date) |&gt;
  summarize(
    entries_day = sum(total_ridership, na.rm = TRUE),
    .groups = &quot;drop&quot;
  ) |&gt;
  left_join(hour_cov, by = c(&quot;station_complex_id&quot;, &quot;date&quot;)) |&gt;
  mutate(hours_present = replace_na(hours_present, 0L))</code></pre>
</div>
<div id="weather-feature-engineering" class="section level2">
<h2>Weather Feature Engineering</h2>
<p>We integrate daily weather observations and engineer two key
features:</p>
<ul>
<li><strong><code>heatwave</code></strong>: Binary indicator for periods
with max temperature ≥ 90°F for consecutive days</li>
<li><strong><code>storm</code></strong>: Binary indicator for
significant precipitation events (≥ 1 inch)</li>
</ul>
<pre class="r"><code>panel_station_day &lt;- panel_station_day |&gt;
  left_join(weather_clean, by = &quot;date&quot;) |&gt;
  arrange(station_complex_id, date) |&gt;
  group_by(station_complex_id) |&gt;
  mutate(
    heat_day = if_else(!is.na(tmax) &amp; tmax &gt;= params$heat_threshold_f, 1L, 0L),
    heat_roll = slide_int(heat_day, sum, .before = params$heat_consec_days - 1, .complete = TRUE),
    heatwave = if_else(!is.na(heat_roll) &amp; heat_roll &gt;= params$heat_consec_days, 1L, 0L),
    storm = if_else(!is.na(prcp) &amp; prcp &gt;= params$storm_threshold_in, 1L, 0L),
    weather_missing = as.integer(is.na(tmax) | is.na(prcp))
  ) |&gt;
  ungroup()</code></pre>
</div>
<div id="event-geocoding-spatial-matching" class="section level2">
<h2>Event Geocoding &amp; Spatial Matching</h2>
<p>This critical step links textual event data to subway stations:</p>
<ol style="list-style-type: decimal">
<li><strong>Filter</strong> to large-scale Manhattan events (parades,
races, festivals)</li>
<li><strong>Geocode</strong> text addresses to coordinates using
ArcGIS/OSM</li>
<li><strong>Spatial join</strong> events to nearest station within 800m
radius</li>
<li><strong>Flag</strong> affected station-hours and station-days</li>
</ol>
<pre class="r"><code>event_radius_m &lt;- params$event_radius_m

# Filter to Manhattan focus events
events_manhattan &lt;- events_clean |&gt;
  filter(is.na(event_borough) | str_detect(event_borough, &quot;manhattan&quot;))

focus_types &lt;- c(&quot;parade&quot;, &quot;athletic&quot;, &quot;race&quot;, &quot;tour&quot;, &quot;street&quot;, &quot;block&quot;, &quot;festival&quot;, &quot;fair&quot;)
events_focus &lt;- events_manhattan |&gt;
  filter(!is.na(event_type)) |&gt;
  filter(purrr::reduce(focus_types, \(acc, key) acc | str_detect(str_to_lower(event_type), key), .init = FALSE)) |&gt;
  distinct(event_id, .keep_all = TRUE) |&gt;
  mutate(event_id = as.character(event_id))

# Load geocode cache
cache_path &lt;- &quot;data/events/nyc_large_events_geocoded.csv&quot;
if (file.exists(cache_path)) {
  geo_cache &lt;- readr::read_csv(
    cache_path,
    col_types = cols(.default = col_guess(), event_id = col_character()),
    show_col_types = FALSE
  )
} else {
  geo_cache &lt;- tibble(event_id = character(), lon = numeric(), lat = numeric())
}

# Join with geocoded coordinates
events_focus_geo &lt;- events_focus |&gt;
  left_join(geo_cache, by = &quot;event_id&quot;)

evt_geo_ok &lt;- events_focus_geo |&gt;
  filter(!is.na(lon), !is.na(lat)) |&gt;
  mutate(
    start_hr = floor_date(start_dt, &quot;hour&quot;),
    end_hr = ceiling_date(end_dt, &quot;hour&quot;)
  )

# Spatial matching to stations
if (nrow(evt_geo_ok) == 0) {
  events_station_hour &lt;- tibble(
    station_complex_id = character(),
    date = as.Date(character()),
    hour = integer(),
    event_hour = integer()
  )
} else {
  stn_sf &lt;- st_as_sf(stations_clean, coords = c(&quot;longitude&quot;, &quot;latitude&quot;), crs = 4326) |&gt;
    st_transform(2263)
  evt_sf &lt;- st_as_sf(evt_geo_ok, coords = c(&quot;lon&quot;, &quot;lat&quot;), crs = 4326) |&gt;
    st_transform(2263)

  near_idx &lt;- st_nearest_feature(evt_sf, stn_sf)
  dist_ft &lt;- st_distance(evt_sf, stn_sf[near_idx, ], by_element = TRUE)
  dist_m &lt;- as.numeric(dist_ft) * 0.3048

  evt_joined &lt;- evt_geo_ok |&gt;
    mutate(
      station_complex_id = stn_sf$station_complex_id[near_idx],
      dist_m = dist_m
    ) |&gt;
    filter(dist_m &lt;= event_radius_m) |&gt;
    select(event_id, station_complex_id, start_hr, end_hr, dist_m)

  events_station_hour &lt;- purrr::map_dfr(seq_len(nrow(evt_joined)), function(i) {
    tibble(
      station_complex_id = evt_joined$station_complex_id[i],
      hour_ts = seq(evt_joined$start_hr[i], evt_joined$end_hr[i], by = &quot;1 hour&quot;)
    )
  }) |&gt;
    mutate(date = as_date(hour_ts), hour = hour(hour_ts), event_hour = 1L) |&gt;
    distinct(station_complex_id, date, hour, .keep_all = TRUE) |&gt;
    select(station_complex_id, date, hour, event_hour)
}

# Join events to panels
panel_station_hour &lt;- panel_station_hour |&gt;
  left_join(events_station_hour, by = c(&quot;station_complex_id&quot;, &quot;date&quot;, &quot;hour&quot;)) |&gt;
  mutate(event_hour = if_else(is.na(event_hour), 0L, event_hour))

event_day_by_station &lt;- panel_station_hour |&gt;
  group_by(station_complex_id, date) |&gt;
  summarize(event_day = as.integer(any(event_hour == 1L)), .groups = &quot;drop&quot;)

panel_station_day &lt;- panel_station_day |&gt;
  left_join(event_day_by_station, by = c(&quot;station_complex_id&quot;, &quot;date&quot;)) |&gt;
  mutate(event_day = if_else(is.na(event_day), 0L, event_day))</code></pre>
</div>
<div id="holiday-flags" class="section level2">
<h2>Holiday Flags</h2>
<p>We flag US federal holidays using the <code>timeDate</code> package,
as ridership patterns on holidays often mimic Sunday schedules.</p>
<pre class="r"><code>holidays &lt;- tibble(
  date = as.Date(holidayNYSE(2024:2025)),
  is_holiday = &quot;Yes&quot;
)

panel_station_day &lt;- panel_station_day |&gt;
  left_join(holidays, by = &quot;date&quot;) |&gt;
  mutate(
    is_holiday = case_match(
      is_holiday,
      NA ~ &quot;No&quot;,
      &quot;Yes&quot; ~ &quot;Yes&quot;
    )
  )</code></pre>
</div>
<div id="baseline-calculation" class="section level2">
<h2>Baseline Calculation</h2>
<p>To calculate percent change in ridership, we define the baseline as
the <strong>median ridership</strong> for each station by day-of-week
and month, accounting for weekly and seasonal patterns.</p>
<pre class="r"><code>panel_station_day &lt;- panel_station_day |&gt;
  mutate(
    dow = wday(date, label = TRUE, week_start = 1),
    month = month(date)
  )

baseline_sd &lt;- panel_station_day |&gt;
  group_by(station_complex_id, dow, month) |&gt;
  summarize(baseline_sd = median(entries_day, na.rm = TRUE), .groups = &quot;drop&quot;)

panel_station_day &lt;- panel_station_day |&gt;
  left_join(baseline_sd, by = c(&quot;station_complex_id&quot;, &quot;dow&quot;, &quot;month&quot;)) |&gt;
  mutate(
    pct_change = log((entries_day + 1) / (baseline_sd + 1))
  )

baseline_sh &lt;- panel_station_hour |&gt;
  mutate(
    dow = wday(date, label = TRUE, week_start = 1),
    month = month(date)
  ) |&gt;
  group_by(station_complex_id, dow, month, hour) |&gt;
  summarize(baseline_sh = median(total_ridership, na.rm = TRUE), .groups = &quot;drop&quot;)

panel_station_hour &lt;- panel_station_hour |&gt;
  mutate(
    dow = wday(date, label = TRUE, week_start = 1),
    month = month(date)
  ) |&gt;
  left_join(baseline_sh, by = c(&quot;station_complex_id&quot;, &quot;dow&quot;, &quot;month&quot;, &quot;hour&quot;)) |&gt;
  mutate(
    hourly_pct_change = log((total_ridership + 1) / (baseline_sh + 1))
  )</code></pre>
</div>
<div id="output-summary" class="section level2">
<h2>Output Summary</h2>
<pre class="r"><code>cat(&quot;Panel Station Day:&quot;, nrow(panel_station_day), &quot;rows\n&quot;)</code></pre>
<pre><code>## Panel Station Day: 80905 rows</code></pre>
<pre class="r"><code>cat(&quot;Panel Station Hour:&quot;, nrow(panel_station_hour), &quot;rows\n&quot;)</code></pre>
<pre><code>## Panel Station Hour: 1921163 rows</code></pre>
<pre class="r"><code>cat(&quot;Stations:&quot;, n_distinct(panel_station_day$station_complex_id), &quot;\n&quot;)</code></pre>
<pre><code>## Stations: 123</code></pre>
<pre class="r"><code>cat(&quot;Date range:&quot;, as.character(min(panel_station_day$date, na.rm = TRUE)), &quot;to&quot;, as.character(max(panel_station_day$date, na.rm = TRUE)), &quot;\n&quot;)</code></pre>
<pre><code>## Date range: 2024-01-01 to 2025-10-19</code></pre>
<pre class="r"><code>cat(&quot;Heatwave days:&quot;, sum(panel_station_day$heatwave == 1, na.rm = TRUE), &quot;\n&quot;)</code></pre>
<pre><code>## Heatwave days: 1108</code></pre>
<pre class="r"><code>cat(&quot;Storm days:&quot;, sum(panel_station_day$storm == 1, na.rm = TRUE), &quot;\n&quot;)</code></pre>
<pre><code>## Storm days: 2090</code></pre>
<pre class="r"><code>cat(&quot;Event-affected station-days:&quot;, sum(panel_station_day$event_day == 1, na.rm = TRUE), &quot;\n&quot;)</code></pre>
<pre><code>## Event-affected station-days: 2504</code></pre>
<pre class="r"><code>if (params$write_outputs) {
  write_parquet(panel_station_day, file.path(params$outputs_dir, &quot;panel_station_day_indexed.parquet&quot;))
  write_parquet(panel_station_hour, file.path(params$outputs_dir, &quot;panel_station_hour_indexed.parquet&quot;))
  cat(&quot;\nParquet files written to:&quot;, params$outputs_dir, &quot;\n&quot;)
}</code></pre>
<p>The final datasets (<code>panel_station_day</code> and
<code>panel_station_hour</code>) are exported as Parquet files for
efficient use in our analysis pipeline.</p>
<hr />
</div>
</div>
<div id="summary" class="section level1">
<h1>Summary</h1>
<p>Our integrated dataset provides comprehensive coverage of Manhattan
subway ridership and its potential drivers:</p>
<p><strong>Ridership:</strong> 1,921,163 hourly observations across 123
Manhattan stations (January 2024–October 2025), totaling over 1255
million rides.</p>
<p><strong>Weather:</strong> 2,151 daily observations from Central Park
(2020-2025), including 35 heat wave days (≥90°F) and 18 major storm
events (≥1 inch precipitation) during our study period.</p>
<p><strong>Events:</strong> 149,524 large permitted events covering
2024-2025, with 53,977 in Manhattan. Events show strong seasonality
(summer/fall peaks) and include major NYC happenings.</p>
<p><strong>Stations:</strong> Complete geospatial coverage of 155
Manhattan subway stations, enabling spatial analysis of ridership
patterns and proximity-based event impacts.</p>
<p>All four datasets align temporally and spatially, providing
comprehensive infrastructure for analyzing <strong>weather and event
impacts</strong> on station-level subway ridership across Manhattan’s
22-month study period.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
