---
title: "EDA"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

```{r message=FALSE, warning=FALSE, include=FALSE}
# Load Packages
library(tidyverse)
library(arrow)
library(viridis)
library(patchwork)
```

```{r setup, include=FALSE}
# Set defaults for knitting
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE, 
                      warning = FALSE,
                      fig.width = 10, 
                      fig.height = 6)

# Set default theme
theme_set(theme_bw() +
  theme(
    plot.title = element_text(face = "bold", size = 14),
    plot.subtitle = element_text(size = 11)))

# Use viridis for discrete color and fill scales
scale_colour_discrete = function(...) scale_colour_viridis_d(...)
scale_color_discrete = function(...) scale_color_viridis_d(...)
scale_fill_discrete = function(...) scale_fill_viridis_d(...)
```

```{r}
# Load data
panel_station_hour_df = read_parquet("data/derived/panel_station_hour_indexed.parquet")
panel_station_day_df = read_parquet("data/derived/panel_station_day_indexed.parquet")
station_summary_df = read_csv("data/derived/station_summary.csv")
event_df = read_csv("data/events/nyc_large_events_2024_2025.csv")
event_location_df = read_csv("data/events/nyc_large_events_geocoded.csv")

# Cumulative system ridership by day and add year variable
panel_station_day_df = 
  panel_station_day_df |>
  group_by(date) |>
  mutate(day_ridership_system = sum(entries_day),
         year = year(date))

# Calculate baseline system ridership using median
baseline_system_day = 
  panel_station_day_df |>
  filter(is_holiday == "No") |>
  group_by(year, month, dow) |>
  summarise(baseline_system_day = median(day_ridership_system, na.rm = TRUE), .groups = "drop")

# Join baseline system ridership with data
panel_station_day_df =
  panel_station_day_df |>
  left_join(baseline_system_day, by = c("year", "month", "dow")) |>
  mutate(
    pct_change_system = log( (day_ridership_system + 1) / (baseline_system_day + 1) ))
```

# Ridership vs Day

```{r}
# Ridership by Day-of-Week
daily_ridership_df = 
  panel_station_day_df |>
  filter(station_id == 1) |>
  select(date, dow, is_holiday, day_ridership_system)

# Ridership over time
p_riders_over_time =
  daily_ridership_df |>
  filter(is_holiday == "No") |>
  ggplot(aes(x = date, y = day_ridership_system / 1e6, color = dow)) +
  geom_point(size = 0.8) +
  geom_smooth(method = "loess", 
              span = 0.3, 
              linewidth = 1.5,
              se = FALSE) +
  labs(
    x = "Date",
    y = "System Ridership (M)",
    color = "Day-of-Week")

# Boxplot
p_dow_riders = 
  daily_ridership_df |>
  filter(is_holiday == "No") |>
  ggplot(aes(x = dow, y = day_ridership_system, fill = dow)) +
  geom_boxplot(alpha = 0.9) +
  theme(
    axis.title.y = element_blank(),
    axis.text.y  = element_blank(),
    axis.ticks.y = element_blank()) +
  labs(
    x = "Day-of-Week")

# Patchwork plot
(p_riders_over_time + p_dow_riders) + 
  plot_layout(guides = "collect",
              widths = c(2, 1)) &
  plot_annotation(title = "Ridership by Day") &
  theme(legend.position = "none")


```

# Ridership vs Weather

```{r}
p_temp =
  panel_station_day_df |>
  filter(is_holiday == "No") |>
  distinct(date, tmax, dow, day_ridership_system) |>
  ggplot(aes(x = tmax, y = day_ridership_system / 1e6)) +
  geom_point(size = 1) +
  geom_smooth(method = "loess", 
              span = 1, 
              linewidth = 1.5,
              color = "#E67E22",
              se = FALSE) +
  facet_grid(.~dow) +
  theme(
    legend.position = "none") +
  labs(
    title = "Ridership vs Max Temperature",
    x = "Temperature (F)",
    y = "System Ridership (M)")

p_prcp =
  panel_station_day_df |>
  filter(is_holiday == "No",
         prcp > 0,
         snow == 0) |>
  group_by(date) |>
  summarise(pct_change_system = first(pct_change_system),
            prcp = first(prcp)) |>
  ggplot(aes(x = prcp, y = pct_change_system)) +
  geom_point() +
  geom_smooth(method = "loess", 
              span = 1, 
              linewidth = 1.5,
              color = "#2C7BE5",
              se = FALSE) +
  scale_x_log10() +
  labs(
    title = "Ridership Change by Rainfall",
    x = "Rain (in)",
    y = "Log Percent Change from Baseline")

p_snow =
  panel_station_day_df |>
  filter(is_holiday == "No",
         snow > 0) |>
  group_by(date) |>
  summarise(pct_change_system = first(pct_change_system),
             snow = first(snow)) |>
  ggplot(aes(x = snow, y = pct_change_system)) +
  geom_point() +
  geom_smooth(method = "loess", 
              span = 1, 
              linewidth = 1.5,
              color = "#0FB9B1",
              se = FALSE) +
  scale_x_log10() +
  labs(
    title = "Ridership Change by Snowfall",
    x = "Snowfall (in)",
    y = "Log Percent Change from Baseline")

p_temp / (p_prcp + p_snow)
```


